/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSobreRouteImport } from './routes/_site.sobre'
import { Route as SiteOndeEstamosRouteImport } from './routes/_site.onde-estamos'
import { Route as SiteContatoRouteImport } from './routes/_site.contato'
import { Route as SiteCardapioRouteImport } from './routes/_site.cardapio'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSobreRoute = SiteSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOndeEstamosRoute = SiteOndeEstamosRouteImport.update({
  id: '/onde-estamos',
  path: '/onde-estamos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCardapioRoute = SiteCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => SiteRoute,
} as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/cardapio': typeof SiteCardapioRoute
  '/contato': typeof SiteContatoRoute
  '/onde-estamos': typeof SiteOndeEstamosRoute
  '/sobre': typeof SiteSobreRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRoutesByTo {
  '/cardapio': typeof SiteCardapioRoute
  '/contato': typeof SiteContatoRoute
  '/onde-estamos': typeof SiteOndeEstamosRoute
  '/sobre': typeof SiteSobreRoute
  '/': typeof SiteIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/cardapio': typeof SiteCardapioRoute
  '/_site/contato': typeof SiteContatoRoute
  '/_site/onde-estamos': typeof SiteOndeEstamosRoute
  '/_site/sobre': typeof SiteSobreRoute
  '/_site/': typeof SiteIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardapio'
    | '/contato'
    | '/onde-estamos'
    | '/sobre'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cardapio'
    | '/contato'
    | '/onde-estamos'
    | '/sobre'
    | '/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  id:
    | '__root__'
    | '/_site'
    | '/_site/cardapio'
    | '/_site/contato'
    | '/_site/onde-estamos'
    | '/_site/sobre'
    | '/_site/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sobre': {
      id: '/_site/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SiteSobreRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/onde-estamos': {
      id: '/_site/onde-estamos'
      path: '/onde-estamos'
      fullPath: '/onde-estamos'
      preLoaderRoute: typeof SiteOndeEstamosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contato': {
      id: '/_site/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cardapio': {
      id: '/_site/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof SiteCardapioRouteImport
      parentRoute: typeof SiteRoute
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteCardapioRoute: typeof SiteCardapioRoute
  SiteContatoRoute: typeof SiteContatoRoute
  SiteOndeEstamosRoute: typeof SiteOndeEstamosRoute
  SiteSobreRoute: typeof SiteSobreRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteCardapioRoute: SiteCardapioRoute,
  SiteContatoRoute: SiteContatoRoute,
  SiteOndeEstamosRoute: SiteOndeEstamosRoute,
  SiteSobreRoute: SiteSobreRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
